// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Department struct {
	ID       string `json:"id"`
	DeptName string `json:"deptName"`
	Team     string `json:"team"`
}

type Employee struct {
	ID     string      `json:"id"`
	Name   string      `json:"name"`
	Age    int         `json:"age"`
	Salary int         `json:"salary"`
	Dept   *Department `json:"dept"`
}

type NewDepartment struct {
	ID       string `json:"id"`
	DeptName string `json:"deptName"`
}

type NewEmployee struct {
	Name   string `json:"name"`
	Age    int    `json:"age"`
	Salary int    `json:"salary"`
}
